services:
  - type: web
    name: resumepro-api
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r support/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: resumepro-db
          property: connectionString

  - type: pgsql
    name: resumepro-db
    plan: free
